
	.definelabel GROUP_ACDC_TOWN, 0x0
	.definelabel MAP_ACDC_TOWN, 0x0

	.definelabel EVENT_402, 0x402
	.definelabel EVENT_403, 0x403

	.definelabel CS_VAR_IMM, 0xff

	.definelabel NPCScript_StationaryNPC, 0x809f6cc
	
	.definelabel OW_UP, 0
	.definelabel OW_UP_RIGHT, 1
	.definelabel OW_RIGHT, 2
	.definelabel OW_DOWN_RIGHT, 3
	.definelabel OW_DOWN, 4
	.definelabel OW_DOWN_LEFT, 5
	.definelabel OW_LEFT, 6
	.definelabel OW_UP_LEFT, 7

	.definelabel oNaviStats_Attack, 0x1
	.definelabel oNaviStats_Speed, 0x2
	.definelabel oNaviStats_Charge, 0x3
	.definelabel oNaviStats_MaxBaseHP, 0x3e
	.definelabel oNaviStats_CurHP, 0x40
	.definelabel oNaviStats_MaxHP, 0x42
	.definelabel oNaviStats_Folder1Tag2, 0x57
	.definelabel oNaviStats_ChipShuffle, 0x60
	
	.definelabel eOverworldNPCObject0_X, 0x20057d4
